version: '2'
services:
  eventstore:
    image: eventstore/eventstore
    entrypoint: /bin/bash
    command:
    - -c
    - 'grep -q -F "IntIpAdvertiseAs: $$(hostname -i)" /etc/eventstore/eventstore.conf  ||
      echo "IntIpAdvertiseAs: $$(hostname -i)" >> /etc/eventstore/eventstore.conf &&
      grep -q -F "ExtIpAdvertiseAs: $$(hostname -i)" /etc/eventstore/eventstore.conf  ||
      echo "ExtIpAdvertiseAs: $$(hostname -i)" >> /etc/eventstore/eventstore.conf &&
      /entrypoint.sh'

    environment:
    - EVENTSTORE_CLUSTER_SIZE=3
    - EVENTSTORE_CLUSTER_DNS=eventstore
    - EVENTSTORE_CLUSTER_GOSSIP_PORT=2112
    - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:${external_http_port}/
    - EVENTSTORE_EXT_HTTP_PORT=${external_http_port}
    - EVENTSTORE_EXT_TCP_PORT=${external_tcp_port}
    
    ports:
    - ${external_http_port}:${external_http_port}/tcp
    - ${external_tcp_port}:${external_tcp_port}/tcp


#more /etc/eventstore/eventstore.conf
#more /var/log/eventstore/20*/*.log
#rm more /var/log/eventstore/20*/*.log

