version: '2'
services:
  eventstore:
    image: eventstore/eventstore
    entrypoint: /bin/bash
    command: ['-c', 'grep -q -F "IntIpAdvertiseAs: $$(hostname -i)" /etc/eventstore/eventstore.conf  || echo "IntIpAdvertiseAs: $$(hostname -i)" >> /etc/eventstore/eventstore.conf && grep -q -F "ExtIpAdvertiseAs: $$(hostname -i)" /etc/eventstore/eventstore.conf  || echo "ExtIpAdvertiseAs: $$(hostname -i)" >> /etc/eventstore/eventstore.conf && /entrypoint.sh']
    environment:
      - EVENTSTORE_CLUSTER_SIZE=3
      - EVENTSTORE_CLUSTER_DNS=eventstore
      - EVENTSTORE_CLUSTER_GOSSIP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:${load_balancer_external_http_port}/

  eventstore-lb:
    image: rancher/lb-service-haproxy:v0.5.9
    ports:
      - ${load_balancer_external_http_port}:${load_balancer_external_http_port}/tcp
      - ${load_balancer_external_tcp_port}:1113/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'


#more /etc/eventstore/eventstore.conf
#more /var/log/eventstore/20*/*.log
#rm more /var/log/eventstore/20*/*.log

