version: '2'
.catalog:
  name: GES
  version: 0.0.1.0-ges
  description: |
    (Experimental) GES Cluster.
  minimum_rancher_version: v0.59.0
  maintainer: "Jérôme Rx <jerome@rouaix.eu>"
  uuid: ges-0
  questions:
    - variable: "load_balancer_external_http_port"
      description: "External load balancer http port"
      label: "LB http port"
      required: true
      default: 2113
      type: "int"
    - variable: "load_balancer_external_tcp_port"
      description: "External load balancer tcp port"
      label: "LB tcp port"
      required: true
      default: 1113
      type: "int"

services:
  eventstore:
    scale: 3
    start_on_create: true
  eventstore-lb:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        path: ''
        priority: 1
        protocol: http
        service: eventstore
        source_port: ${load_balancer_external_http_port}
        target_port: ${load_balancer_external_http_port}
      - hostname: ''
        path: ''
        priority: 2
        protocol: tcp
        service: eventstore
        source_port: ${load_balancer_external_tcp_port}
        target_port: ${load_balancer_external_tcp_port}
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000

