version: '2'
.catalog:
  name: GES
  version: 0.0.1.0-ges
  description: |
    (Experimental) GES Cluster.
  minimum_rancher_version: v0.59.0
  maintainer: "Jérôme Rx <jerome@rouaix.eu>"
  uuid: ges-0
  questions:
    - variable: "internal_http_port"
      label: "Internal http (and gossip) port"
      required: true
      default: 2112
      type: "int"
    - variable: "internal_tcp_port"
      label: "Internal tcp port"
      required: true
      default: 1112
      type: "int"
    - variable: "external_http_port"
      label: "External http port"
      required: true
      default: 2113
      type: "int"
    - variable: "external_tcp_port"
      label: "External tcp port"
      required: true
      default: 1113
      type: "int"

services:
  eventstore:
    scale: 3
    start_on_create: true

