name: Vault
description: |
  This template installs a Vault server with optional configuration items, including backing store
version: 1.0-test-rancher1
category: Platform
maintainer: Randal Cobb <randy.cobb@nordstrom.com>
license: 
projectURL: http://www.nordstrom.com/tech/givingBack
