version: '2'

services:
  redmine-datavolume:
    image: "busybox"
    volumes:
      - /home/redmine/data
      - /var/lib/mysql
      - /var/log/redmine
    labels:
      io.rancher.container.start_once: true
    entrypoint: ["/bin/true"]

  db:
    restart: always
    image: mariadb
    volumes_from:
    - redmine-datavolume
    labels:
      io.rancher.sidekicks: redmine-datavolume
      io.rancher.container.pull_image: always
    environment:
    - MYSQL_USER=redmine
    - MYSQL_PASSWORD=${DB_PASS}
    - MYSQL_ROOT_PASSWORD=${DB_PASS}
    - MYSQL_DATABASE=redmine_production

  redmine:
    image: sameersbn/redmine:3.3.2-1
    labels:
      io.rancher.sidekicks: db,redmine-datavolume
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
    - PORT=${PORT}
    - TZ=${TZ}
    - DB_PASS=${DB_PASS}
    - DB_ADAPTER=mysql2
    - DB_HOST=db
    - DB_USER=redmine
    - DB_NAME=redmine_production
    - REDMINE_SECRET_TOKEN=${REDMINE_SECRET_TOKEN}
    - SMTP_ENABLED=false
    - IMAP_ENABLED=false
    volumes_from:
    - redmine-datavolume
