.catalog:
  name: "Wordpress"
  version: "v0.2-bitnami"
  description: "Blog tool, publishing platform and CMS based on bitnami images"
  uuid: Wordpress-1
  minimum_rancher_version: v0.51.0
  questions:    
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
wordpress:
