version: '2'
catalog:
  name: selenium
  version: 3.8.1-bohrium
  minimum_rancher_version: v1.5.0
  questions:
    - variable: "SELENIUM_VERSION"
      label:
      description: |
      type: enum
      options:
        - 3.8.1-bohrium
        - 3.8.1-aluminum
        - 3.7.1-cadmium
        - 3.7.1-beryllium
        - 3.7.1-argon
        - 3.7.0-arsenic
        - 3.6.0-darmstadtium
        - 3.6.0-copper
        - 3.6.0-bromine
        - 3.6.0-americium
        - 3.5.3-boron
        - 3.5.3-astatine
        - 3.5.2-antimony
        - 3.5.1-aluminum
        - 3.5.0-argon
        - 3.4.0-francium
        - 3.4.0-einsteinium
        - 3.4.0-dysprosium
        - 3.4.0-chromium
        - 3.4.0-bismuth
