.catalog:
  name: "zinst-repository"
  version: "7.0.5"
  description: "Infra as a code by your own packages. http://zinst.me"
  uuid: zinstrepo-0
  minimum_rancher_version: v1.5.5
  questions:    
    - variable: public_port
      description: "public port to access the zinst repository"
      label: "Public Port"
      required: true
      default: "8080"
      type: "int"

zinst-repository:
  retain_ip: true
  scale: 1
  start_on_create: true
