name: selenium
description: |
  selenium hub and nodes
version: 0
category: Test Automation
maintainer: "ramz sivagurunathan <ramzthecoder@gmail.com>"
license: "Apache License 2.0"
projectURL: http://www.seleniumhq.org/
