.catalog:
    name: Elasticsearch Cluster
    version: 5.3.0-rancher1
    description: 3-Node Elasticsearch Cluster with Kibana

    questions:
        - variable: "cluster_name"
          type: "string"
          required: true
          label: "Cluster name"
          description: "Name of the Elasticsearch Cluster"
          default: "es-cluster"
        
        - variable: "heap_size"
          type: "string"
          required: true
          label: "Heap size"
          description: "Heap size to be allocated for Java"
          default: "512m"
        
        - variable: "mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size!"
          default: 1073741824
        
        - variable: "kibana_port"
          type: "int"
          required: true
          label: "Public kibana port"
          description: "Public port where kibana will be accessible"
          default: 5601

        - variable: "minimum_master_nodes"
          type: "int"
          required: true
          label: "# of minimum Master Nodes"
          description: "Set the number of required master nodes to reach quorum. Sets initial scale to this value as well"
          default: 2

        - variable: "initial_data_nodes"
          type: "int"
          required: true
          label: "# of initial nodes"
          description: "Set the initial number of nodes"
          default: 1


es-master:
  scale: ${minimum_master_nodes}

es-node:
  scale: ${initial_data_nodes}